#!/bin/sh -e

VERSION=1.0

GREEN='\033[1;32m'
RED='\033[1;31m'
YELLOW='\033[1;33m'
NC='\033[0m'

HOST=$(uname -n)

echo -e "${YELLOW}Starting...${NC}"

sudo /run/current-system/sw/bin/nixos-rebuild switch --flake .#$HOST $@

echo -e "${GREEN}Switch to new generation complete!${NC}"
