#!/usr/bin/env bash
set -ex

usage() { echo "Usage: $0 [-h <string:hostname>] [-u <string:username>] [-i <boolean:impermanence>]" 1>&2; exit 1; }

HOST=$(uname -n)
USERNAME="s33d"

while getopts ":h:u:i" o; do
    case "${o}" in
        h)
            HOST=${OPTARG}
            ;;
        u)
            USERNAME=${OPTARG}
            ;;
        i)
            IMPERMANENT='true'
            ;;
        *)
            usage
            ;;
    esac
done
shift $((OPTIND-1))

check_installer() {
  if [ -e /etc/NIXOS ]; then
    echo -e "\e[1;32mRunning in the NixOS installer environment.\e[0m"
  else
    echo -e "\e[1;31mNot running in the NixOS installer environment.\e[0m"
    exit 1
  fi
}

cleanup() {
  rm -rf nixos-config-main.zip nixos-config-main nixos-config
}

download_config() {
  curl -LJ0 https://github.com/abstracts33d/nixos-config/archive/main.zip -o nixos-config-main.zip
  unzip nixos-config-main.zip
  mv nixos-config-main nixos-config
  cd nixos-config
}

run_disko() {
  sudo nix run --extra-experimental-features nix-command --extra-experimental-features flakes \
    github:nix-community/disko -- --mode zap_create_mount ./hosts/nixos/$HOST/disk-config.nix
}

setup_files() {
  sudo mkdir -p /mnt/etc/nixos
  sudo cp -r * /mnt/etc/nixos
  cd /mnt/etc/nixos

  mkdir -p /root/.ssh
  touch /root/.ssh/known_hosts
  ssh-keyscan -t ed25519 github.com >> /root/.ssh/known_hosts
}

setup_ssh_keys() {
  mkdir -p /mnt/home/${USERNAME}/.ssh
  chown nixos /mnt/home/${USERNAME}/.ssh

  chown nixos /root/.ssh/id_ed25519{,.pub}

  mkdir -p /mnt/home/${USERNAME}/.keys
  chown nixos /mnt/home/${USERNAME}/.keys
  cp --preserve=all /root/.ssh/id_ed25519 /mnt/home/${USERNAME}/.keys/id_ed25519
  cp --preserve=all /root/.ssh/id_ed25519.pub /mnt/home/${USERNAME}/.keys/id_ed25519.pub
  chmod 600 /mnt/home/${USERNAME}/.keys/id_ed25519{,.pub}
}

setup_impermanent_ssh_keys() {
  if [ -n "$IMPERMANENT" ]; then
    mkdir -p /mnt/persist/home/${USERNAME}/.keys
    chown nixos /mnt/persist/home/${USERNAME}/.keys
    cp --preserve=all /root/.ssh/id_ed25519 /mnt/persist/home/${USERNAME}/.keys/id_ed25519
    cp --preserve=all /root/.ssh/id_ed25519.pub /mnt/persist/home/${USERNAME}/.keys/id_ed25519.pub
    chmod 600 /mnt/persist/home/${USERNAME}/.keys/id_ed25519{,.pub}
  fi
}

link_home_dir() {
  ln -s /mnt/home/${USERNAME} /home/${USERNAME} # Used to grab initial secrets
}

install_nixos() {
  sudo nixos-install --flake .#$HOST $@
  rm -rf /mnt/home/${USERNAME}/${USERNAME} || true # Remove the home dir symlink
}

prompt_reboot() {
  read -p "Do you want to reboot now? (y/yes) " choice
  case "$choice" in
  y|Y|yes|YES ) echo -e "\e[1;32mRebooting...\e[0m" && sudo reboot;;
  * ) echo -e "\e[1;33mReboot skipped.\e[0m";;
  esac
}

cleanup
check_installer
download_config
run_disko
setup_files
setup_ssh_keys
setup_impermanent_ssh_keys
link_home_dir
install_nixos
cleanup
prompt_reboot
